io:
  github:
    joemsu:
      jpa:
        properties:
          hibernate.hbm2ddl.auto: update
spring:
  jta:
    log-dir: ./
    atomikos:
      datasource:
        customer:
          xa-properties:
            url: jdbc:mysql://127.0.0.1:3306/customer?characterEncoding=UTF-8&amp;useSSL=false
            user: root
            password: "123456"
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          unique-resource-name: customer
          max-pool-size: 25
          min-pool-size: 3
          max-lifetime: 20000
          borrow-connection-timeout: 10000
        order:
          xa-properties:
            url: jdbc:mysql://127.0.0.1:3306/orders?characterEncoding=UTF-8&amp;useSSL=false
            user: root
            password: "123456"
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          unique-resource-name: order
          max-pool-size: 25
          min-pool-size: 3
          max-lifetime: 20000
          borrow-connection-timeout: 10000
    enabled: true